sudo: required
services:
  - docker

before_install:
  - docker build -t gujral1997/react-docker -f Dockerfile.dev .

script:
  - docker run gujral1997/react-docker npm run test -- --coverage --watchAll=false
