sudo: required
services:
  - docker

before_install:
  - docker build -t gujral1997/react-docker -f Dockerfile.dev .

script:
  - docker run gujral1997/react-docker npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-680029890655"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
